FileVersion = 1
Dependencies = {corlib = "*", FastNoiseLite-beef = "*", stb_image_write = "*"}

[Project]
Name = "example"
TargetType = "BeefGUIApplication"
StartupObject = "example.Program"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
