FileVersion = 1

[Project]
Name = "FastNoiseLite-beef"
TargetType = "BeefLib"
StartupObject = "FastNoiseLite_beef.Program"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\fastnoiselited.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\fastnoiselite.lib"]
