FileVersion = 1

[Project]
Name = "FastNoiseLite-beef"
TargetType = "BeefLib"
StartupObject = ""

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\fastnoiselite_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\fastnoiselit.lib"]
