FileVersion = 1

[Project]
Name = "FastNoiseLite-beef"
TargetType = "BeefLib"
StartupObject = ""

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\windows\\fastnoiselited.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\fastnoiselite.lib"]
